#! /bin/bash
# Copyright (C) 2017 The Qt Company
# This file is part of elfutils.
#
# This file is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# elfutils is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

. $srcdir/backtrace-subr.sh

# The binary is generated by compiling backtrace-child without debug
# information, but with -mapcs-frame -fno-omit-frame-pointer.
# -mapcs-frame makes some functions store the frame pointer in r11.
# gcc docs say one should also specify -fno-omit-frame-pointer, but
# result seems to be independent of this.
#
# gcc -static -O2 -mapcs-frame -fno-omit-frame-pointer \
#     -mfloat-abi=hard -I ../ -I ../lib/ -D_GNU_SOURCE \
#     -pthread -o backtrace.arm.fp.exec backtrace-child.c \
#     --sysroot=/my/arm/sysroot
#
# Then strip the .eh_frame section from the binary:
#
# strip -R .eh_frame backtrace.arm.fp.exec
#
# The core is generated by calling the binary with --gencore

check_core arm.fp --allow-unknown
